workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.nuveloMarketplace
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: com.example.nuveloMarketplace
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter pub get
      - name: Set up code signing
        script: |
          cd mobile/ios
          xcode-project use-profiles --archive-method app-store
      - name: Build IPA
        script: |
          cd mobile
          flutter build ipa --release --build-name=0.1.1 --build-number=2 --export-options-plist="$HOME/export_options.plist"
    artifacts:
      - mobile/build/ios/ipa/*.ipa
      - mobile/build/ios/archive/*.xcarchive
      - mobile/build/ios/archive/Runner.xcarchive/dSYMs/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
  android-release:
    name: Android Release
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter pub get
      - name: Build App Bundle
        script: |
          cd mobile
          flutter build appbundle --release
    artifacts:
      - mobile/build/app/outputs/bundle/release/app-release.aab
