services:
  - type: web
    name: nuvelo-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 4000
    healthCheckPath: /health
