name: nuvelo_marketplace
description: Nuvelo — Discover. Connect. Trade. Anywhere.
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/env
